In [1]:
import torch

In [19]:
a = torch.randn(2, 4, 4)
a

tensor([[[-0.4366, -0.6616, -0.8655,  1.3869],
         [-0.0788, -0.6572, -2.3165, -0.6691],
         [-1.0360, -1.0938, -0.4994, -0.7439],
         [-0.2051,  1.8198,  1.5264, -0.3290]],

        [[-0.0797,  0.4151, -1.7254,  0.1034],
         [-0.1304,  0.2779, -0.2762, -0.5377],
         [ 0.8842,  0.1721, -1.3750,  0.7470],
         [-1.6714,  0.8215, -0.2294, -0.6720]]])

In [20]:
a.mean(dim=1)

tensor([[-0.4391, -0.1482, -0.5387, -0.0888],
        [-0.2493,  0.4217, -0.9015, -0.0898]])

In [14]:
p = (a != 0).sum(dim=1)
p

tensor([[3, 4, 4, 3],
        [2, 4, 4, 3]])

In [16]:
s = a.sum(dim=1)
s

tensor([[13, 20, 17, 14],
        [ 7, 14, 19, 14]])

In [12]:
c = s / p
c

tensor([[5.0000, 3.5000, 3.0000, 4.5000],
        [   nan, 7.5000, 2.5000, 5.0000],
        [8.0000, 7.0000, 6.0000, 7.0000],
        [7.0000, 2.0000, 2.0000, 3.5000]])